In [31]:
from bs4 import BeautifulSoup
import pandas as pd

website = "30 Most Popular Movies Right Now_ What to Watch In Theaters and Streaming __ Rotten Tomatoes – Movie and TV News.html"

file = open(website, encoding = "utf-8")

res = file.read()
# print(res)

soup = BeautifulSoup(res, "html.parser")
# print(soup)

movie_title = []
ratings = []
year = []

movies = soup.find_all('div', class_="row countdown-item-title-bar")
for movie in movies:
    movie_title.append(movie.h2.a.text)
    ratings.append(movie.find('span', class_="tMeterScore").text)

for movie_year in movies:
    year.append(movie_year.find('span', class_="subtle start-year").text)
year

df = pd.DataFrame({
    'Movie_Titles' : movie_title,
    'Ratings' : ratings,
    'Years' : year
})
df
# df.isnull().sum()

                               Movie_Titles Ratings   Years
0          Transformers: Rise of the Beasts     53%  (2023)
1       Spider-Man: Across the Spider-Verse     96%  (2023)
2                        The Little Mermaid     67%  (2023)
3                             The Boogeyman     63%  (2023)
4     Are You There God? It's Me, Margaret.     99%  (2023)
5                                    Fast X     56%  (2023)
6                                BlackBerry     98%  (2023)
7                               The Machine     27%  (2023)
8                                   Reality     92%  (2023)
9                               Flamin' Hot     68%  (2023)
10           Guardians of the Galaxy Vol. 3     82%  (2023)
11                                Blue Jean     94%  (2022)
12                               Past Lives     97%  (2023)
13              The Super Mario Bros. Movie     58%  (2023)
14                 Avatar: The Way of Water     76%  (2022)
15               Guy Ritchie's The Covenant     83%  (2023)
16                                Bumblebee     91%  (2018)
17                                Nefarious     33%  (2023)
18                                     Sisu     93%  (2022)
19                     You Hurt My Feelings     95%  (2023)
20                     John Wick: Chapter 4     94%  (2023)
21                           Leave No Trace     80%  (2022)
22                          About My Father     36%  (2023)
23  Dungeons & Dragons: Honor Among Thieves     90%  (2023)
24                             Transformers     57%  (2007)
25                                 My Fault          (2023)
26                         A Beautiful Life     50%  (2023)
27     The Angry Black Girl and Her Monster     88%  (2023)
28                                  Missing     87%  (2023)
29                                      Air     92%  (2023)

In [52]:
from bs4 import BeautifulSoup
import pandas as pd

website = "Fact-checks _ PolitiFact.html"

file = open(website, encoding = "utf-8")

res = file.read()
# print(res)

soup = BeautifulSoup(res, "html.parser")
# print(soup)

statements =[]
sources = []
dates = []

statement = soup.find_all('article', class_="m-statement")
for state in statement:
    statements.append(state.find('div', class_="m-statement__quote").text.strip())
statements

source = soup.find_all('article', class_="m-statement")
for state in source:
    sources.append(state.find('a').text.strip())
sources

date = soup.find_all('div', class_="m-statement__meta")
for state in date:
    # date_on = state.div.text.strip().split('stated on')[1]
    date_on = state.div.text.strip()[9:]
    dates.append(date_on.split('in')[0])
dates

df = pd.DataFrame({
    'Statements' : statements,
    'Names' : sources,
    'Dates' : dates
})
df

,Statements,Names,Dates
0,“President Trump’s tariffs are costing New Yor...,Kirsten Gillibrand,"March 19, 2026"
1,"""There's been numerous other occasions over th...",Donald Trump,"May 18, 2026"
2,“San Diego mosque shooters identified as trans...,Social Media,"May 19, 2026"
3,"Video shows U.S. Rep. Byron Donalds saying, “I...",X posts,"May 14, 2026"
4,An American passenger on the cruise ship invol...,X posts,"May 6, 2026"
5,“Florida is the only state in the nation kicki...,Kathy Castor,"April 29, 2026"
6,"In 2020, “Amy Acton called off Ohio’s election...",Vivek Ramaswamy,"April 24, 2026"
7,Imágenes muestran a personas “infectadas con H...,TikTok posts,"May 8, 2026"
8,"“Today, there are more children sleeping in Ne...",Christine Quinn,"March 5, 2026"
9,“The average IRS tax refund is up 11% compared...,Nicholas Langworthy,"March 31, 2026"
10,Gasoline prices have “come down very substanti...,Donald Trump,"May 7, 2026"
11,Congress passed the 1965 Voting Rights Act bec...,Byron Donalds,"May 4, 2026"
12,Republicans “want you to pay $1 Billion for a ...,Marcy Kaptur,"May 5, 2026"
13,Proposed data centers in New York state would ...,Liz Krueger,"March 5, 2026"
14,“California only has ‘enough’ oil and gas supp...,X posts,"May 6, 2026"
15,"“Consumer confidence is way up.""",Donald Trump,"May 4, 2026"
16,"From January 2025 to January 2026, “hate crime...",Sam Sutton,"March 11, 2026"
17,"“Under federal law, you cannot engage in parti...",Fentrice Driskell,"April 29, 2026"
18,Imagen muestra que “950 inmigrantes derrumbaro...,Instagram posts,"April 26, 2026"
19,“As a result of the 'Big Beautiful Bill' 15 mi...,Bernie Sanders,"April 22, 2026"
20,“Secret Service remains unpaid” during the par...,Tim Scott,"April 26, 2026"
21,“Graham Platner blames Maine’s women for getti...,Pine Tree Results PAC,"April 26, 2026"
22,Video shows “unedited raw security footage” of...,Social Media,"April 26, 2026"
23,“We are right now producing more oil than Saud...,Donald Trump,"April 23, 2026"
24,"Since the 2020 census, Florida has ""moved from...",Ron DeSantis,"April 27, 2026"
25,"“Tras el atentado a Trump”, en la cena de corr...",Social Media,"April 26, 2026"
26,"U.S. Rep. Byron Donalds voted ""against three p...",Jay Collins,"April 20, 2026"
27,"""There's two ways of calculating percentage"" d...",Robert F. Kennedy Jr.,"April 22, 2026"
28,"“With one dose of ibogaine, more than 80% of p...",Joe Rogan,"April 18, 2026"
29,“Newly released FOIA door logs show that forme...,X posts,"April 21, 2026"

In [83]:
mileage.remove('Mileage')

In [86]:
from bs4 import BeautifulSoup
import pandas as pd

website = "Certified used Mercedes-Benz for sale.html"

file = open(website, encoding = "utf-8")
res = file.read()
# print(res)

soup = BeautifulSoup(res, "html.parser")
# print(soup)

names = []
mileages = []
prices = []
review_Count = []
dealer_names = []
ratings = []

car_name = soup.find_all('a', class_="vehicle-card-link")
for c_name in car_name:
    names.append(c_name.find('h2', class_="title").text)
names

car_mileage = soup.find_all('div', class_="mileage")
for c_mileage in car_mileage:
    mileage.append(c_mileage.text.strip())
mileages = mileage.remove('Mileage')

car_price = soup.find_all('div', class_="price-section")
for c_price in car_price:
    prices.append(c_price.span.text.strip())
prices

car_review_count = soup.find_all('div', class_="vehicle-dealer")
for c_rcount in car_review_count:
    review_Count.append(c_rcount.find('span', class_="sds-rating__link").text.strip())
    dealer_names.append(c_rcount.find('div', class_="dealer-name").text.strip())
    
review_Count
dealer_names

car_ratings = soup.find_all('div', class_="sds-rating")
for c_ratings in car_ratings:
    ratings.append(c_ratings.find('span', class_="sds-rating__count").text.strip())
ratings


df = pd.DataFrame({
    'Names' : names,
    'Mileage' : mileages,
    'Prices' : prices,
    'Review_Count' : review_Count,
    'Dealer_names' : dealer_names,
    'Ratings' : ratings
})
df

ValueError: All arrays must be of the same length

In [81]:
mileage

['28,744 mi.',
 '25,771 mi.',
 '22,374 mi.',
 '10,595 mi.',
 '33,622 mi.',
 '12,477 mi.',
 '22,383 mi.',
 '49,332 mi.',
 '37,688 mi.',
 '19,521 mi.',
 '14,420 mi.',
 '34,555 mi.',
 '16,474 mi.',
 '10,233 mi.',
 '6,800 mi.',
 '54,467 mi.',
 '8,690 mi.',
 '8,158 mi.',
 '8,401 mi.',
 '24,958 mi.',
 '49,278 mi.']